### ISSUE TITLE
Umbrella documentation issue

### ISSUE THREAD

**Issue by pieterlange** [kubernetes-incubator/kube-aws#90]
There's a bit of documentation already out there, but some of it is hard to find and a lot of it is outdated. The move to the dedicated repo included a bunch of improvements of which nearly all are mostly documented in github issues.

Proposal for documentation checklist:
- [ ] Cluster lifecycle documentation
   -  relevant: #61
- [x] Compiling instructions (in README, #162)
- [x] Feature overview (in README, #162)
- [x] README.md cleanup? (too much info on one page) #162 
- [ ] List of third party blog posts (with dates/versions)
- [x] Add `ROADMAP.md` #162 
- [x] GOALS in README
  - Done in a way other than initially planned
- [x] Fixes
   - [x] [Documentation on external DNS seems out of date](https://github.com/coreos/kube-aws/issues/110) #162 
- [ ] Currently un-documented pre-requisites
   - [x] [Internet Gateway needs to be added to VPC before cluster can be created](https://github.com/coreos/kube-aws/issues/120) #162 
   - [x] [KubernetesCluster tag is not applied to existing objects](https://github.com/coreos/kube-aws/issues/135) #162 
   - [x] [What's the smallest instance size I can use?](https://github.com/coreos/kube-aws/issues/138) #162 
   - [x] [Creating new cluster in brand new VPC requires "DNS Hostnames" setting to be turned on](https://github.com/coreos/kube-aws/issues/119) #162 
   - [ ] [List of IAM permissions](https://github.com/coreos/kube-aws/issues/88)
- [ ] Custom configuration
   - [ ] [Docker container log limit](https://github.com/coreos/kube-aws/issues/134)
- [ ] FAQ/Gotchas (in `Documentation/kubernetes-on-aws-limitations.md`, #162)
   - [x] [does hostPort not work on kube-aws/CoreOS?](https://github.com/coreos/kube-aws/issues/91)

**Comment by mumoshu** [comment]
Thanks for starting this!

* Regarding the compiling instructions part, I guess we'd better document at least the fact we need to `git clone` the repo under `$GOPATH/src/github.com/coreos` like I've explained in https://github.com/coreos/kube-aws/issues/87#issuecomment-262660786
* Should we document about experimental features, too?
* Anyone likes the idea of something like `GOALS.md` which I've mentioned in https://github.com/coreos/kube-aws/issues/59#issuecomment-261824684?

**Comment by aholbreich** [comment]
> Anyone likes the idea of something like GOALS.md which I've mentioned in #59 (comment)?

yes, me ;)

**Comment by mumoshu** [comment]
Added "Fixes", "Currently un-documented pre-requisites", "Custom configuration" to the list.

**Comment by mumoshu** [comment]
@aholbreich FYI, regarding one of your comment:

> Allows management of several clusters in convenient way

Probably in a way other than you might have expected but the work is ongoing at #238.
